import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import Navbar from "../components/Nav";
import HeroImageEdit from "../components/settings/HeroImageEdit";
import HeroTextEdit from "../components/settings/HeroTextEdit";
import {useStore} from "../shared";
import HeroCommunities from "../components/settings/HeroCommunities";
import CommunityTile from "../components/Community/CommunityTile";
import {communities} from "../utils/constants";
import {IoAddCircleSharp} from 'react-icons/io';
import {ActionTypes} from "../shared/constants";

const Settings = () => {
   const [editMode, setEditMode] = useState(null);
    const [state, dispatch] = useStore();

    const { heroText, heroImage, featured } = state;

    const addAsFeatured = (comm) => {
        const alreadyExists = featured.find(item => item.id === comm.id);
        if(alreadyExists) {
            alert('Community Already Featured');
            return;
        }
        if(featured.length === 3) {
            alert('Maximum 3 communities can be featured');
            return;
        }
        dispatch({
            type: ActionTypes.SET_FEATURED,
            payload: [...featured, comm]
        })
    }
   return (
      <div>
         <Head>
            <title>Settings</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Navbar />
         <div className="px-8 py-5 lg:px-16 md:px-10 md:py-5">
            <h1 className="text-3xl font-Aboreto md:text-5xl">
               Customize your dashboard
            </h1>
             <div className="flex lg:hidden justify-center mt-10 flex-col items-center">
                 <Image src="/assets/404.svg" height="200px" width="200px" alt="404" />
                 <h1 className="text-3xl">Editing not enabled on smaller devices</h1>
             </div>
            <div className="hidden lg:flex justify-between items-start mt-10">
               <div className="w-[40%] border-[1px] border-background p-4 min-h-[50vh]">
                  <p className="text-xl mb-5">Dashboard</p>
                  {!editMode && (
                     <div className="flex flex-col items-start">
                        <button
                           className="bg-background p-4 mb-5 w-full text-start"
                           onClick={() => setEditMode("text")}
                        >
                           Edit Hero Text
                        </button>
                        <button
                           className="bg-background p-4 mb-5 w-full text-start"
                           onClick={() => setEditMode("image")}
                        >
                           Edit Hero Image
                        </button>
                         <button
                             className="bg-background p-4 mb-5 w-full text-start"
                             onClick={() => setEditMode("community")}
                         >
                             Edit Featured Communities
                         </button>
                     </div>
                  )}
                  {editMode === "text" ? (
                     <HeroTextEdit setEditMode={setEditMode} />
                  ) : null}

                  {editMode === "image" ? (
                     <HeroImageEdit setEditMode={setEditMode} />
                  ) : null}
                   {editMode === "community" ? (
                       <HeroCommunities setEditMode={setEditMode} />
                   ) : null}
               </div>
               <div className="w-[60%] border-[1px] border-background p-4 min-h-[50vh]">
                  {editMode == "text" && (
                     <div>
                        <div className={`w-[60%] p-12 lg:flex justify-center flex-col items-center h-[80vh] rounded-3xl`} style={{background: heroText.bgColor}}>
                           <h1 className="font-Aboreto pl-4 lg:text-3xl lg:mt-8 xl:text-5xl">
                               {heroText.title}
                           </h1>
                           <p className="p-6 font-Lato">
                               {heroText.description}
                           </p>
                        </div>
                     </div>
                  )}

                  {editMode == "image" && (
                     <div className=" hidden md:block md:w-[60%] lg:w-[40%] md:rounded-l-xl md:h-[70vh]">
                        <img
                           src={heroImage}
                           width="1000px"
                           height="1500px"
                           alt="coder"
                           className="object-cover rounded-l-xl"
                        />
                     </div>
                  )}
                   {
                       editMode === "community" && (
                           <div className="flex flex-wrap">
                               {
                                   communities.map((community) => (
                                       <div key={community.id} className="flex items-center justify-around">
                                           <CommunityTile  data={community} pg="half" edit={false} />
                                           <button className="ml-5 bg-blue-500 rounded-md px-5 py-2 text-white" onClick={() => addAsFeatured(community)}>Add As Featured</button>
                                       </div>
                                   ))
                               }
                           </div>
                       )
                   }
                  {!editMode && (
                    <div>Make it your own community, by giving it the look you want</div>
                  )}
               </div>
            </div>
         </div>
      </div>
   );
};

export default Settings;
